creation_rules:
  - path_regex: '^k8s/(postgres/postgres(-backup|-role)?|server/(server|migrator))\.secret\.sops\.yaml$'
    encrypted_regex: "^(data|stringData)$"
    age:
      - age1ms5klvwgurjz6mfecl375wzg50dfyzv607x8esw9wr8th39r4desd6x6wh
      - age1nd5ew9mgyd5fldxgxa3eh9dht2q7exft2jeas7eer3mthg5f8fusg7psn7

stores:
  yaml:
    indent: 2
