apiVersion: v1
kind: Secret
metadata:
  name: opswarden-migrator-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:+VP0BdnZfxrRHmq8gKi/e8vyD6gfX/xaZB3PT7Ah3miW+MlKKDhYjrE41Uwy4rJXsg1bS0pRDAaqKNTtN2IwIw7JTuRcAmydWu1ALBFY9gtBDlAIZDyXkNysTIbvjR/5VSPzaIDwcLJulLEnyFlAWtDNZL5lmg==,iv:UFf/ShaQxbeSBtVNBYw/tyUsGLU+52bgNQ7D5pMNhnU=,tag:3CVb/hFn6miCu1lT1NI6Iw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYlNCcUJmYkFaY2VtUHFn
        K3VPYUhkb0ZyZFh6ajdyZnhBN3dvY2hwZm1nCjBEMERTcWJXK1lIVlRYOHpXUEJn
        d2ZTNEZleGFOYzJyRGNlQldDTWx0YVUKLS0tIG9nUnE4UDVvZitoWlRCMWJ0bXJR
        ODcwMExMeGNOVFBSMFVWdlJ0NWhYR28KIOhzMu75FmFKSYaJjSOsaDWD9xtcJzx+
        tCjndguEgTZCkA0xDICh9CH6/gXsUAwawG+3eTUpmyFj36icbUCH9g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ms5klvwgurjz6mfecl375wzg50dfyzv607x8esw9wr8th39r4desd6x6wh
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSjQ3dFRPbHRSb1lEOVRD
        VHZpRjUrTUgxd1QvV0M3WWYvZFNwcVI3MkNNCkhOQTZRbTVYRkRtZDU4T0F4YXkr
        bFFkckFBYVJqZ283QnorTjAwaDV2NFUKLS0tIDFBSEtpdW45ai9QdTVyak1Ua0pa
        QndVS1JPTGRITXZvb0JlMmVDeGZaOEkKD8Rffpd/esNFQMJ57Veq3tFwJJUVE4r4
        VZuEHoyGHyzRL1FRU//k0d1Zvg6S2MU4E+snhQ6eU+tYIFWGbV7npQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nd5ew9mgyd5fldxgxa3eh9dht2q7exft2jeas7eer3mthg5f8fusg7psn7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T11:24:07Z"
  mac: ENC[AES256_GCM,data:kdqxGerr7mmv1+pHrKIF4LpvnvtMBEbUBMQRUwQpkN6ZTB3uLvf5XQ8vojdQUcmBlxw2kdrLyY4Uh27ws3lxLr6LgrL8JgZlPwcMHyljWNQ1gH7+7uDCNaTUrYw+YbuJZa6qu0MNjZYJcT09CcIIibG0zau6pV1dwYhi2CwrlQQ=,iv:uOtIaHOMBYjuwaRuU52gaKxW6RHVVow8botczPP71LY=,tag:vT9FRb3+dS3oRLEvCd4thQ==,type:str]
  version: 3.13.1
