apiVersion: v1
kind: Secret
metadata:
  name: opswarden-server-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:OtRzHKn0PagEc1jWcbiFc8z6sLrkvwk4hO+1zBFO82o/zSkVQgObpX9NKOhW7tiDK/3biNVhMMLJHg5yaQUq64qFD9a/MRFWnf045YiiRz8jFD5ybrqPCD8o176sYzvkV1jg9TgXVHyKnQOVxnp28CCEZkU6,iv:ccaXvE6V5CUdW6mFuMG5Xs1c5QqmtTst9AyzFPkkdbE=,tag:PTmOFeRkvZokvkWdlCYRfA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:xIOZG45Y+4asuBU5t+WSD2eHazqeEajkv6qXwpJJhVqDtn0o30Ad/FEz5VpXoLwX+EHKeWxYsegDzb/iAXZhVg==,iv:AzETRSRaxRZh1oTgsjBowAQi4/2GopmVsBmAyR3a2nw=,tag:5UPa89VggPWvIglfDiREyA==,type:str]
  OPSWARDEN_VAULT_KEY: ENC[AES256_GCM,data:8F2h3d+xJBH8AsjPvnYql8xl7pwsI5OQZwsRxTJVjUlUKgQxL/YWk8EIgyaLVYuVD7IJBImjTHKZtxJ8EmF+pA==,iv:AG0EQ0pGm4rudz6WCdr6ywPW2Mfi3IKYc83uU9T0mPI=,tag:aD9rqPc5zVT9J5y6xv2JHA==,type:str]
  OPSWARDEN_KICKOFF_TOKEN: ENC[AES256_GCM,data:9Yn/Vv4J9dRJZzNSDubR8fCi0igArKyPiTCwxfulAxf60yUarpRD6YI/o8rL5fb9NWA1nw+fb+drmSHjjcMw/A==,iv:f1teUwVwsifaesvTlpG0mnWFFm2yxkZ3LVgY6+Z/FMY=,tag:xPbYELfQdj17h08h9Ovmqw==,type:str]
  GOOGLE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:44cANW7zmRXHv6gbvCP31sIEaKqn2MESOulARuaKGgJ5Wz95EnCgxdFBcGACHoe4rdjJxGEktahcG/Mbhlz5pvT9wfFFRi8=,iv:BoUyhx4xVmmRMa8tvbi5h5V52x1UAeEbPAGLbQdAuD8=,tag:OjHRj0QUkXcbQsXtcXVQAQ==,type:str]
  GOOGLE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:tdMiZmvrrYJY6Jfik4htlZYX/e5zErtllE9A/x0Jc7NCjrc=,iv:2MFsS3Dcf1aZtkluIANCoEs1mrGpCOgFQkPEiooRqNA=,tag:53t3jUjnEtCsAHgJQE2gEw==,type:str]
  GITHUB_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:ZKIVOtpaG+Qzva6EaUzJgEja2VQ=,iv:kqKYD2icITVeG3EFVVIcPl09VYLY9sauRZvCyVDE8xA=,tag:RxA6YP7xOoFgIt0OE7efIA==,type:str]
  GITHUB_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Y6ob2uI5h38o713A4sAtjy9/ecMe4LsJkFJxgtrFIkrKVREVg86JHw==,iv:ZDGEGk/sBqAwiIe38HiiAwXwFAI6EDvz40pf1dzoNbs=,tag:fYYzPyhpfhtTXfghgbo2ow==,type:str]
  GIPHY_API_KEY: ENC[AES256_GCM,data:D8/CRN3ao4g960HDZEVd5bToK7d9JeLNA5/PViUmrrk=,iv:4UHDFjBQy1b3NGdkgX9nimzrB14PQaaCB56fxDYCDyo=,tag:A/+Hty0CTGq7/fPHxx3R9A==,type:str]
  GITHUB_AUTH_CLIENT_ID: ENC[AES256_GCM,data:eN/3nDXs5lAJGJjT1QRfCbGQ644=,iv:ME4q0YHm2ZgmscOZgMKgSURPkP04uJZdElCpWpGQ+/0=,tag:uxul6n6tKfc5G4IpR170eQ==,type:str]
  GITHUB_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:C+humdCmeWFUXUJW5KF/pQhvm8O7XlSwKEKGBuaEEsHTbXkIKRo1zw==,iv:TGVG29uxvTLIbDUsM4MR+en9VhR0zpQuY3jdzAU9/u8=,tag:9OTMdvwYK6OAE2pXavWF+A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeVVHa28vTzVzS2pzc2R3
        MWR3NFNxU2YwUUY4bDU4OGtrSlJkOFprcm5ZCjFDUnF0ZTI3QlQ4Y3NwZFVJMWZq
        T001T3l2YXFVVHJSQ08rWFhQdnBOcGsKLS0tIHl1UEM5WTQraGJWMmpEd3BEQjAy
        M3FpQ0RLdTNid01SK29aeFdud1h4TDAKeWrVRnZ30PmuX5gs+RBz7y2V/U36ZUJe
        aS8tErekGizaY7Np/B5aZMgFTapDxHIG6v6koYmv+gXEpqfslPPm3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ms5klvwgurjz6mfecl375wzg50dfyzv607x8esw9wr8th39r4desd6x6wh
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaTFRZjg0WnFvV2Z1MHoz
        eTBydVJjWTN4R040UnFOUlgzdzVHWXFjL0ZjCnRjSDNDamZnOU5nVzBYYklGRUhq
        Ui83TEZQeFZRWWgzb242akFjYSt3cUEKLS0tIGM3ajRaSmR0RjUxN1ZDYVQxd2NR
        L1FldGVWcUNDN3ZGaUVmWkFvMHpYc0EKyEWtjTN9VZsm/aGuxwD3qHpQ2RZR06Hd
        n7AxT470EIcHiL5pmSbIwcHiZKJ84S1/hoIgG9MxWWjVMre053dL0w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nd5ew9mgyd5fldxgxa3eh9dht2q7exft2jeas7eer3mthg5f8fusg7psn7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T18:03:56Z"
  mac: ENC[AES256_GCM,data:Y0kjL3xXDd6FzHOWxs8EMx4Ip/FNrwUfygJgXM4AytudZl0q9W9jOl9RSJNNZCILe3Y+2v/cHh18vHl/pgMho9s7RyGrB40QznKQbl5FrYF0u+LqLfjJmSPUM+C80Nxm30pYUM9v8BGv4Ey9ANxl5JqB/7KcFrVZ9EwlKuZCGfs=,iv:wpZALiFgCu0TyqQclczrsdBZXPgam0aGxk0C1vaSd+M=,tag:y0jjCCeYRwyNw4PLGWe39A==,type:str]
  version: 3.13.1
