apiVersion: v1
kind: Secret
metadata:
  name: opswarden-server-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:OtRzHKn0PagEc1jWcbiFc8z6sLrkvwk4hO+1zBFO82o/zSkVQgObpX9NKOhW7tiDK/3biNVhMMLJHg5yaQUq64qFD9a/MRFWnf045YiiRz8jFD5ybrqPCD8o176sYzvkV1jg9TgXVHyKnQOVxnp28CCEZkU6,iv:ccaXvE6V5CUdW6mFuMG5Xs1c5QqmtTst9AyzFPkkdbE=,tag:PTmOFeRkvZokvkWdlCYRfA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:xIOZG45Y+4asuBU5t+WSD2eHazqeEajkv6qXwpJJhVqDtn0o30Ad/FEz5VpXoLwX+EHKeWxYsegDzb/iAXZhVg==,iv:AzETRSRaxRZh1oTgsjBowAQi4/2GopmVsBmAyR3a2nw=,tag:5UPa89VggPWvIglfDiREyA==,type:str]
  OPSWARDEN_VAULT_KEY: ENC[AES256_GCM,data:8F2h3d+xJBH8AsjPvnYql8xl7pwsI5OQZwsRxTJVjUlUKgQxL/YWk8EIgyaLVYuVD7IJBImjTHKZtxJ8EmF+pA==,iv:AG0EQ0pGm4rudz6WCdr6ywPW2Mfi3IKYc83uU9T0mPI=,tag:aD9rqPc5zVT9J5y6xv2JHA==,type:str]
  OPSWARDEN_KICKOFF_TOKEN: ENC[AES256_GCM,data:9Yn/Vv4J9dRJZzNSDubR8fCi0igArKyPiTCwxfulAxf60yUarpRD6YI/o8rL5fb9NWA1nw+fb+drmSHjjcMw/A==,iv:f1teUwVwsifaesvTlpG0mnWFFm2yxkZ3LVgY6+Z/FMY=,tag:xPbYELfQdj17h08h9Ovmqw==,type:str]
  GOOGLE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:44cANW7zmRXHv6gbvCP31sIEaKqn2MESOulARuaKGgJ5Wz95EnCgxdFBcGACHoe4rdjJxGEktahcG/Mbhlz5pvT9wfFFRi8=,iv:BoUyhx4xVmmRMa8tvbi5h5V52x1UAeEbPAGLbQdAuD8=,tag:OjHRj0QUkXcbQsXtcXVQAQ==,type:str]
  GOOGLE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:HHa/ma0t5fvEC35f82Uu8u9FS62xA5QpVjR7wyfj4UALkJo=,iv:qPHdZR+9doPlJTA41WOUYvKj6PmaPVbaIplcNSQhcQ4=,tag:RCbJolCwMRd8u0Z06STylQ==,type:str]
  GITHUB_OAUTH_CLIENT_ID: ""
  GITHUB_OAUTH_CLIENT_SECRET: ""
  GIPHY_API_KEY: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeVVHa28vTzVzS2pzc2R3
        MWR3NFNxU2YwUUY4bDU4OGtrSlJkOFprcm5ZCjFDUnF0ZTI3QlQ4Y3NwZFVJMWZq
        T001T3l2YXFVVHJSQ08rWFhQdnBOcGsKLS0tIHl1UEM5WTQraGJWMmpEd3BEQjAy
        M3FpQ0RLdTNid01SK29aeFdud1h4TDAKeWrVRnZ30PmuX5gs+RBz7y2V/U36ZUJe
        aS8tErekGizaY7Np/B5aZMgFTapDxHIG6v6koYmv+gXEpqfslPPm3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ms5klvwgurjz6mfecl375wzg50dfyzv607x8esw9wr8th39r4desd6x6wh
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaTFRZjg0WnFvV2Z1MHoz
        eTBydVJjWTN4R040UnFOUlgzdzVHWXFjL0ZjCnRjSDNDamZnOU5nVzBYYklGRUhq
        Ui83TEZQeFZRWWgzb242akFjYSt3cUEKLS0tIGM3ajRaSmR0RjUxN1ZDYVQxd2NR
        L1FldGVWcUNDN3ZGaUVmWkFvMHpYc0EKyEWtjTN9VZsm/aGuxwD3qHpQ2RZR06Hd
        n7AxT470EIcHiL5pmSbIwcHiZKJ84S1/hoIgG9MxWWjVMre053dL0w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nd5ew9mgyd5fldxgxa3eh9dht2q7exft2jeas7eer3mthg5f8fusg7psn7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-28T20:56:34Z"
  mac: ENC[AES256_GCM,data:6oDyZ1rdXE9X8GP4nd6j6eApVjFK5atKuDoVm3tFDb0tVFu9AGavyX6QYfvhGnebU8Z/A9ecrLmm/2bDwFufv7MjsglNfuWp613obxCfz8VsU1ruvEt99A6aZJOEvDYtdelrbmTbbqq+/8YT35Crov70adcLiLcFUcCry74KSd4=,iv:ekVBUF7qWgUENmsnSeHL1ir+s5pjo4LuszEzTy+q+zM=,tag:6T+ge7nrl9VB6Uib124dwg==,type:str]
  version: 3.13.1
