apiVersion: v1
kind: Secret
metadata:
  name: opswarden-server-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:OtRzHKn0PagEc1jWcbiFc8z6sLrkvwk4hO+1zBFO82o/zSkVQgObpX9NKOhW7tiDK/3biNVhMMLJHg5yaQUq64qFD9a/MRFWnf045YiiRz8jFD5ybrqPCD8o176sYzvkV1jg9TgXVHyKnQOVxnp28CCEZkU6,iv:ccaXvE6V5CUdW6mFuMG5Xs1c5QqmtTst9AyzFPkkdbE=,tag:PTmOFeRkvZokvkWdlCYRfA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:vnGffxxtEba0UNWplUDwTFSlSXNA3W+7VLhNYGk4Ho2bBmEVjMc88tAiAaF/u2bpZujizED/HA7NUfx+btTi5A==,iv:FYVmfbLiGiUsfo13NfV+sdfb6gS+g7POZokTr4xGxj4=,tag:zLVTBOI+f43ZcS/lxkvaFw==,type:str]
  OPSWARDEN_VAULT_KEY: ENC[AES256_GCM,data:nCAmGagWpuqKwXksye6chZcLzk4FzVnzzBfyr6FPYF2LINQ32alM8VJl/EJGOG1cwC4KmW8tQsqOXukGdmFWRg==,iv:fzvUHCreQRg9gtjExapd1Z837qiZYygGZ4qZbdzmMaY=,tag:7tlI6xnBWgxf/dP7+Sr2Sg==,type:str]
  OPSWARDEN_KICKOFF_TOKEN: ENC[AES256_GCM,data:f+ErEzIlyd2EGMoA4DjDE7GxYy9gXnI+yP40o6WISlZoJsDIUMwmb79Lqn7CXPFI3bmpxLCsUbl11QzZXf2RLA==,iv:VI+3NYD3RrIavWsSMUGRW13jcBZPEy3MBI25KeHGFzo=,tag:qdEoZkIRiaqDmupuXtI3lw==,type:str]
  GOOGLE_OAUTH_CLIENT_ID: ""
  GOOGLE_OAUTH_CLIENT_SECRET: ""
  GITHUB_OAUTH_CLIENT_ID: ""
  GITHUB_OAUTH_CLIENT_SECRET: ""
  GIPHY_API_KEY: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeVVHa28vTzVzS2pzc2R3
        MWR3NFNxU2YwUUY4bDU4OGtrSlJkOFprcm5ZCjFDUnF0ZTI3QlQ4Y3NwZFVJMWZq
        T001T3l2YXFVVHJSQ08rWFhQdnBOcGsKLS0tIHl1UEM5WTQraGJWMmpEd3BEQjAy
        M3FpQ0RLdTNid01SK29aeFdud1h4TDAKeWrVRnZ30PmuX5gs+RBz7y2V/U36ZUJe
        aS8tErekGizaY7Np/B5aZMgFTapDxHIG6v6koYmv+gXEpqfslPPm3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ms5klvwgurjz6mfecl375wzg50dfyzv607x8esw9wr8th39r4desd6x6wh
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaTFRZjg0WnFvV2Z1MHoz
        eTBydVJjWTN4R040UnFOUlgzdzVHWXFjL0ZjCnRjSDNDamZnOU5nVzBYYklGRUhq
        Ui83TEZQeFZRWWgzb242akFjYSt3cUEKLS0tIGM3ajRaSmR0RjUxN1ZDYVQxd2NR
        L1FldGVWcUNDN3ZGaUVmWkFvMHpYc0EKyEWtjTN9VZsm/aGuxwD3qHpQ2RZR06Hd
        n7AxT470EIcHiL5pmSbIwcHiZKJ84S1/hoIgG9MxWWjVMre053dL0w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nd5ew9mgyd5fldxgxa3eh9dht2q7exft2jeas7eer3mthg5f8fusg7psn7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T11:24:07Z"
  mac: ENC[AES256_GCM,data:1YYCrJPe97WQFxBjlCkYdr4K6uts5P4xf9mCMJ9MET+J+KnGFAyw1e+yWu8bv7Fq+9jvpEKByYmEiNQyMINU4QvVFIfuBjgj9/cHrIONfakp0DSQ4cE8AgO2scbmBomUCuqEwy3TjL19MihpL3q+ARqQYbDW5TOPW39VAALfkBM=,iv:7d4CUKqL29gMTsnjOV1Tfqw1OY4gYvfralPfPtVlEsQ=,tag:ztAsL9DBS5Dj8tUQsuqPoA==,type:str]
  version: 3.13.1
