apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-secret
  namespace: default
type: Opaque
stringData:
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:I//UCvAMYx8iKF98DuaDZUSeT5PVo6RbNQ==,iv:84eODGjRr6+T47w5iNkgh9UjDpW+fZDEzomoKU6Lgj8=,tag:8UvLSvK+Lw2gSJBJ/N+GqA==,type:str]
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:q2hEZUQD2FsbSvKNSUxztVvdJWXux1/mYA==,iv:bdLcHLMlhxJfSMkSXwdB6djJb4XGndb8KMc2VSnnjNY=,tag:rRuH6bwdoP+AhH0uWjAoqQ==,type:str]
  RCLONE_CONFIG_BACKUP_PASSWORD: ENC[AES256_GCM,data:kk6UYESUPbLL7O4qxKDNYh1Lai9+37ooDGGETWQAJd0fk9sBzovx5YNMFw+Vu3QF3T6JkDP60e1psfIQz4UDvpn2/w3jDZM4Xg4T93LMbeDJGCxusvzGftJrd1nFhezWuiGiH/wjHCXKty0=,iv:dV8HBum/d8Z+ErPAw2Z+zDQgNapo7l9GRPaCPyoRsD0=,tag:nSVr9qiiDz3Mw2bqxH2uJw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYVBBaFhDY0JhTmhGMi9G
        dnpWd2lKdHVpMmJLVFg4RHA2aXF1Uzh6b1VrCjFNcEUzQnlUd2FyVkRlcnBtTnVC
        VFNVanU4bk05VDMyZDhnaFNhUk9LczAKLS0tIC9UOTYzQzB6cE5mMGQxSDBGWCtl
        WFY2aVY5U0k5dG55TGNVSmE5UjZHakUKdxvoGeffIgKfVqaoF1YTO4Td+EW3vl5G
        ClQgNcjqwUHQYVjt95QVpWJ3Lw7YQHxYbVfuLhTKVvYPS3t/aXMpyg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ms5klvwgurjz6mfecl375wzg50dfyzv607x8esw9wr8th39r4desd6x6wh
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Y092YTFDcHZBR3dTNUpK
        RVM5Z3VMQmFxdFRRN3BUQmhoc2JURHhxbndZCk9uS1JOQXZIQjEvR3EvQkVzSm1l
        aG1WK3NhdDkvdTgzR3ZYeXZ2eVE2SDAKLS0tIE85UHJBbEdXTUFQYlhFK0xtVTBp
        R1JVRWtkKzZ6YUdPamVPR1RvdjNrODgKXrUuCQMj7pHFteLifppVq7eNtJpZ/g2S
        eyaM5iGfa+Qy/WQ3PlRBk7eWf5IpYkGz48v69oolPno2uQe2BDH3dw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nd5ew9mgyd5fldxgxa3eh9dht2q7exft2jeas7eer3mthg5f8fusg7psn7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T11:24:07Z"
  mac: ENC[AES256_GCM,data:l0FGp5qPW62ipQ4pPRfralv/s4RCdrL7ukqj+QzjwIjLhxXwk6wRu0bYTLSDWwh7GNNduhcRq9B+I7vg5t35kofEmw7rVwCQDVkuFKETY4CbnQBJO3/21VqI09/PHsii/Xqow9dRZ87yt4PYKDVsOnhJcZLG+JwvPdvXyJLbTPM=,iv:9oMf2dObdcOWZMZQxsnFbLWW0iUcxjU32cHRiddXexo=,tag:fKdvmtAnMt83hU2aAFGhuQ==,type:str]
  version: 3.13.1
