apiVersion: v1
kind: Secret
metadata:
  name: postgres-role-secret
  namespace: default
type: Opaque
stringData:
  OWNER_ROLE: ENC[AES256_GCM,data:NzVqj2tSEMv79ND3NhAx,iv:aVn28yjDYVAP+56W0xMJet2PhKrrLquLqhMe6qsahu8=,tag:bdZxAs5VFc07SvfAuCylhw==,type:str]
  MIGRATOR_ROLE: ENC[AES256_GCM,data:iJ76UEhPgg0fj8eGO8Q4YyvU,iv:Bh/bcX2wSb60+jYWVtPaYZLKon5Bg3nkLL2g3OOHcVk=,tag:ueLGZ+IkisT3Imlxv+MVQg==,type:str]
  MIGRATOR_PASSWORD: ENC[AES256_GCM,data:dAwTuQgZxOH+cmJhzbhWmebF+cz+GEqzNZBWxWWe/jJd822Id9DqJBsUbct9tqthXzeI6eBC8wx3qXZ0lhLy/Q==,iv:2GbVd0jDCARABZzeTEtORRUcyAODJKwOpD51QV+zDao=,tag:we8N53OAGMuAj0X0sPLZBA==,type:str]
  RUNTIME_ROLE: ENC[AES256_GCM,data:ooh6haN4VJrHdtwdjazK1zQ=,iv:TK3W44tWGgK/iKfdZJIJICr0JIGqVKNJOv7+XM5694c=,tag:OuSGyozsaR7/KckzvYAK/g==,type:str]
  RUNTIME_PASSWORD: ENC[AES256_GCM,data:nPWRQ7qEPUmntqRI8/cbmzJ7+s6nvhdNSw6pm35kRjuoQ6EUo/xW9OUUrrj4bXW3UWxyxaalwGiXB2BGH1SmnA==,iv:CqGYbGkbgASprfSwVlGPVW9C4mu94jblJv32jBWaxws=,tag:afnsXaGK1Qkw5S8ZwxtkdA==,type:str]
  BACKUP_ROLE: ENC[AES256_GCM,data:TSnUPKr36Cn0uVSn/x8JCA==,iv:xELqxKuxAGS+6Tw/ajn6Kf3z3jOIQzt65A/KMlR7t8w=,tag:0JM3zDswksb4OyM46VaaRw==,type:str]
  BACKUP_PASSWORD: ENC[AES256_GCM,data:IWNLjX89g/ilCZeI5uuXfYrcxYXayA03tpny4CXYsBZpzAnqfDMSAJpNFk0H+LfN+jn+LgiNl7y7e10QsShm9A==,iv:4fKtmJqo4SVw3Vnz13r/8oAGSUsjuWGHggWTNksyaag=,tag:Ltb/uzb9ePlT3tNqb7lEqg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNDNoSmRQaENtOWNkUUhZ
        NHUyYlNpSXcxSGw0SnAxaTlwWjlwY1d3b1NRCkI2dmhncUpaaUo3eDYwWG5pQjZO
        VS9oSUhlUjNZbXhWRkpoZ2poY0tkUDgKLS0tIGdaVTlaRGo5dG56NjN1dFEzVThx
        UW5RMWcxS25vYjNwRDcvQURDdGhTT2cK4D9s0xTkvALDUJWqcEwZiqX/hf2ZGZ2p
        UAGp+eyQaG7PrYePzbpGa5xs/6FGkDwHAF4dsph1/it3dDPxR6VDiA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ms5klvwgurjz6mfecl375wzg50dfyzv607x8esw9wr8th39r4desd6x6wh
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidmdzeW1NRFZjMWlYY2Fn
        MDhteGwxWG0ydW5lUzNkRXlhZ2oxSndENmcwCjViMStIK3kyVHJocWFoNG9tWERS
        TlFpamcxOFc2ZjJiZS9iTjlvVWoxMVkKLS0tIHdsRmdtTTNGZFU3MVgwRlgrZ3lp
        UUF6d2VKV01uQTI1Rk51Ym45M0VMMFEKyrAee4fzlu5KxB65j3ll+bYakNktUTgD
        prN4HyoyO8+Hh8CYtK2AhL9fNTrt3MO6Cld4bpD5n4qknCF3GnVnGA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nd5ew9mgyd5fldxgxa3eh9dht2q7exft2jeas7eer3mthg5f8fusg7psn7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T11:24:07Z"
  mac: ENC[AES256_GCM,data:xihTgUfhpLZ30KrgQeGE1Rh2EVNCxpRqr/b4yjnc86Jj7hM/YHtj/Xne8KFFo9meOk9g4nFK2VQMg5c2yym7kM2Jm2RT9a4qU7INnno3YmbNU3g/gDiO8U7z4MIdb0qmU1UJaF+j10hqhz1rjULoXh8385cIQdI2MEHGhUu+MwQ=,iv:s80FHNIrwF0vpbu2GOKf7FvmjZULMWUnQ13BSJdEi3I=,tag:ea3ofZ1VwPkx8AIA4xGfKg==,type:str]
  version: 3.13.1
