apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  POSTGRES_USER: ENC[AES256_GCM,data:Xs3M3p16r2Qd60Kk5Mh5go2Gaxk=,iv:FgzYp1cFHAuABkgIndPx6hg685FHOf9AW+YmIC8N3As=,tag:NfAHaHvnO3twjWHeqQfJxw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:g+4MzlvWTZ9gjtwJZVy+V3f1Gnt0j2Q0bJbiQI4bW5MYJNZgswgJs3iHFNG22ojch55REBQFtCbtY3+pTgP0z4A7AFkS+heopCAnFtkARyDZna/1wzwt0g==,iv:qBb7adsymLumM7Z8XgSSmmyS3eGEg2IzzBGynLsI0Vo=,tag:AfZV6Vic7b+ykbZIaRBB1Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ejRuNFVUSlE1RVV1ZFF4
        U295VU1CNldpcGhyMlg1Z01CaHpFZFQvMHpJCkVzLzBSdE1lcU5FZTF2eWZhVFdm
        WmdJRzBGNExTcmpRNyt3WGUvUTlLR0EKLS0tIE9pWERnZWNZOU1neFJnN3FJUis3
        NVlzWUtSSVZZL2dvR3p5S0wxcDNpcFUK25dy/iqJCdQLa1gBfsD00SXajx2Up1WL
        Dey9kRicDDrzv7PCdYyhMBBvV6e1PSJSEJ2l94F3HTY4/Nlkou/AVg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ms5klvwgurjz6mfecl375wzg50dfyzv607x8esw9wr8th39r4desd6x6wh
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSkkxa1d4d09QTm5nQm5i
        VHNabmFpa0lpdHRuT1FFSDRLV3dueDZYZVRVCmFnSGdOVUl4Ky95UFhobCt2Mzhu
        Ykg2TlhycmhEUDRTUUY3Zy9UWDA0TDgKLS0tIG9VSGdpUmd1clRpZ1dmaVlmWFBv
        N1lRL1NPUEJjdjdXS3FCQm8yaGFndkEKXM3S+8l3EnElOhjDDY2Rc7Y2F5XA/Kf7
        wITcbv//BNnH9lbooM2gT8RQnCyAfHOZWsu956QX5LAc0tqQC+J3Hw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nd5ew9mgyd5fldxgxa3eh9dht2q7exft2jeas7eer3mthg5f8fusg7psn7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T11:24:18Z"
  mac: ENC[AES256_GCM,data:AN0FeUe8I6dp9HxW/0fDp/HmrJ72HOON/8LA5N5h4rDHgG08hlKsLGsV3ZvB9jlcEqVbkV2RtqYm9PCRBvoeZxZR6dMp/bbQv3xYQU9opDo9QBiwBIPRayDD5RhvvZuUTY3fqX4w20KI4eMgkgVK0SbeQq5wAbYB33EtfjZjXrM=,iv:gIu3GDQZfoZrm5xRt6KUj42PAQUkrV/ikESmbFABdkg=,tag:30eiSFVCBmZc/6EtSB/HSg==,type:str]
  version: 3.13.1
