apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: "CURRENT_ADMIN_ROLE"
  POSTGRES_PASSWORD: "CHANGEME"
  POSTGRES_DB: "CURRENT_DATABASE"
