apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  POSTGRES_USER: ENC[AES256_GCM,data:K06ekHyc3+0smb/G,iv:NgW+RZqKh2qYLwFUmFjlZGg7e5NmfwdZq/Rwu74/AmE=,tag:XKJitvcS+0xligyZbt8O/A==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:ZBNo7JxaN0OOXWCJ,iv:wxM+ZYQxNFzFSHl1Z38MlsBlGKq/oA8884wz6g+Ux5U=,tag:blZmMuYX1hpGbTM4+gonYA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ejRuNFVUSlE1RVV1ZFF4
        U295VU1CNldpcGhyMlg1Z01CaHpFZFQvMHpJCkVzLzBSdE1lcU5FZTF2eWZhVFdm
        WmdJRzBGNExTcmpRNyt3WGUvUTlLR0EKLS0tIE9pWERnZWNZOU1neFJnN3FJUis3
        NVlzWUtSSVZZL2dvR3p5S0wxcDNpcFUK25dy/iqJCdQLa1gBfsD00SXajx2Up1WL
        Dey9kRicDDrzv7PCdYyhMBBvV6e1PSJSEJ2l94F3HTY4/Nlkou/AVg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ms5klvwgurjz6mfecl375wzg50dfyzv607x8esw9wr8th39r4desd6x6wh
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSkkxa1d4d09QTm5nQm5i
        VHNabmFpa0lpdHRuT1FFSDRLV3dueDZYZVRVCmFnSGdOVUl4Ky95UFhobCt2Mzhu
        Ykg2TlhycmhEUDRTUUY3Zy9UWDA0TDgKLS0tIG9VSGdpUmd1clRpZ1dmaVlmWFBv
        N1lRL1NPUEJjdjdXS3FCQm8yaGFndkEKXM3S+8l3EnElOhjDDY2Rc7Y2F5XA/Kf7
        wITcbv//BNnH9lbooM2gT8RQnCyAfHOZWsu956QX5LAc0tqQC+J3Hw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nd5ew9mgyd5fldxgxa3eh9dht2q7exft2jeas7eer3mthg5f8fusg7psn7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-28T20:56:34Z"
  mac: ENC[AES256_GCM,data:BbOS3JTd8x8km6UHdhvJWEso82JBqKBwkoIbx9naFyl7Xu2VrQgtfEl4dvS/bP8xVvf+2GwjuFa4wy9zQ2DOAJv6DMsY7JGAeObntQrfWwRxAGz5lDSWUPcsbBdzqiqETjSnPMAUln3aOarnHU+Lfqio0CnP5C1QM1MmRmMuAGY=,iv:omPABfHDFzlplJO0ZiMXrfIkKXm6pailGl9OwEuDBjo=,tag:3n6TLu2ViX5hNti8fzyWvQ==,type:str]
  version: 3.13.1
