apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-secret
  namespace: default
type: Opaque
data:
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:H3XheWe8uDaLq7wOfiW6LZcbd67qaBQsRJmD8g==,iv:US/rau+369RSK+8T/BXOsPujmtNcFnL3xZT5Ljbh6tg=,tag:3yjwEMRQwVAee90dzU2RtA==,type:str]
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:luTDCQ3Je8Fkd01VGPc+Bt2rN7SmndC2/ak8FX8rZVRoLYXmKnkkGcXCWnJFaebtxmdweleMvSJ07e0s,iv:uUQg0/4ylIlzKUm8EhztYyI0YTAWMuuTjWFbjZC4hOE=,tag:Mz9jw5muXc8qGLjAUHhxRg==,type:str]
  RCLONE_CONFIG_BACKUP_PASSWORD: ENC[AES256_GCM,data:oBih4ztbeJiFW96eubn6BFg41wK+hDu3+/9othzCpqCuDY0Tb3/TFsjm4VI46eM+LyTPzvpUpa92HRaNBZrjXEjJIGjp6WZ07T8Cx/JExKuNUCEdOmuLFEbONaT/JrsWwTphfil4oDb2LKpn975bKuh6j2BtmVFwhZSAHyWkLpmYPtuCeCTAeON+NPHv2+fS,iv:BzPLz+PRVldExhpa8+kn6u8X1+BVG6iM7IAgASW5KMo=,tag:6GzWh0vVWCMADGOAcsJrww==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQUQ5NWdkQm4xcFpJb0Y4
        bThaemo2L1VjbGJYd1B2ZGM2NTBOQUMrQkEwClhRa1M1clMvbTIvUjVnNTBNZUJi
        d3RycGhoUDVCL3drSm42R21aSEQyTlkKLS0tIE90NmhhVG9aQ3A4MkcrSTVIU2M2
        Kzlodk5aM2E5WHpvTGw3RWwxL2JWMzQKirgimTVoGdCQ9ACX2gX1A88cxSzAzs/9
        /29tbnc+A/k35qAGJSaNk9tpPxWWl98XP1lUV1AWwFIHvmEWUcgF5g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ms5klvwgurjz6mfecl375wzg50dfyzv607x8esw9wr8th39r4desd6x6wh
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMWRVRUJLVk1KTHp2bHpz
        V0F4a3g1cGxVbXN0U0tKQk1leWxqaTQrZVJnCjRnVUtiejUwUUluZEczbWRaMEJy
        YW1VNVZIcmF1Ujk1VG9wL1lkalgxaVUKLS0tIEZubjRVL2tTUDdmSWgwMFZmVjB1
        MEhQOGkrWTM5bWgwZVlnWWxvV2NkOUEKIm5t1peR/0oG6EaFeH84eyHuiT3ebHhm
        158OTgdzeDVHgUDLsJmEpjbfC0uXjqAQcjFYQtWOHQqUVS4qto5jsQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nd5ew9mgyd5fldxgxa3eh9dht2q7exft2jeas7eer3mthg5f8fusg7psn7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-30T19:06:16Z"
  mac: ENC[AES256_GCM,data:dy2pJNv94KqZUnveVOmcc0t7VKgc3ZzACX9R8li3KY7GNTDutPNai9ubDZyC9LEyjnz16FhOcpTgrgLld7C0fIOCyIm8QOtCEWlYvlY8YLoqJHgkTAid7lVDv129krzSYNKsZ/zpX3Gyfw6+YPDln+PZZWR54vzEzEFGH27RZDk=,iv:MXm4epOFt0mWBm1o/vodVVVfjiLye6+i7QBImZ55m1s=,tag:0ZAulAhx4s7uJvrPGeAiRw==,type:str]
  version: 3.13.1
