apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  POSTGRES_USER: ENC[AES256_GCM,data:/AyF3IOuFQyxQVTB,iv:igOE9+4MkvT54dFqRzC93i4S1DJsb1Av4mCD9MmtW8Y=,tag:jTWLRX1SBrscX95ICpDpog==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:zDCUZXYJj6NAbnSS,iv:NwPg4c3kDoh2lULwRLKUFBPAipDyaSwD4KPHzNCOU/4=,tag:wOU5et4M3sH0oM57e0bELA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ejRuNFVUSlE1RVV1ZFF4
        U295VU1CNldpcGhyMlg1Z01CaHpFZFQvMHpJCkVzLzBSdE1lcU5FZTF2eWZhVFdm
        WmdJRzBGNExTcmpRNyt3WGUvUTlLR0EKLS0tIE9pWERnZWNZOU1neFJnN3FJUis3
        NVlzWUtSSVZZL2dvR3p5S0wxcDNpcFUK25dy/iqJCdQLa1gBfsD00SXajx2Up1WL
        Dey9kRicDDrzv7PCdYyhMBBvV6e1PSJSEJ2l94F3HTY4/Nlkou/AVg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ms5klvwgurjz6mfecl375wzg50dfyzv607x8esw9wr8th39r4desd6x6wh
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSkkxa1d4d09QTm5nQm5i
        VHNabmFpa0lpdHRuT1FFSDRLV3dueDZYZVRVCmFnSGdOVUl4Ky95UFhobCt2Mzhu
        Ykg2TlhycmhEUDRTUUY3Zy9UWDA0TDgKLS0tIG9VSGdpUmd1clRpZ1dmaVlmWFBv
        N1lRL1NPUEJjdjdXS3FCQm8yaGFndkEKXM3S+8l3EnElOhjDDY2Rc7Y2F5XA/Kf7
        wITcbv//BNnH9lbooM2gT8RQnCyAfHOZWsu956QX5LAc0tqQC+J3Hw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nd5ew9mgyd5fldxgxa3eh9dht2q7exft2jeas7eer3mthg5f8fusg7psn7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T11:21:02Z"
  mac: ENC[AES256_GCM,data:08B0Cy74ZtIV4z1YRTS48rBzm62Mjs1uNpmGmwiA61Jr04JvNlpndv5F5pLXSk8Ne08vt8nc3nlrDXv0amdhlaFv7TTfCDaJLENM2UwXREBWt1KJgBajVVCmnRmxz6M5e+p2g1wJNSfC9CZsEK5MG1C4uurxSGiLbdL9mDMKu3Q=,iv:qV2lDeSO9O90bD6HDCWirgST4K/PevJJjY5mnWnN2Js=,tag:53gH03oQRF5bCLGc6eOe2Q==,type:str]
  version: 3.13.1
